import os
from dotenv import load_dotenv

load_dotenv()

MODE = os.getenv("MODE", "TESTNET")
AUTO_TRADE = os.getenv("AUTO_TRADE", "false").lower() == "true"

BINANCE_API_KEY = os.getenv("BINANCE_API_KEY")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET")

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

INTERVAL = "15m"
KLINE_LIMIT = 250

PERFORMANCE_REPORT_SECONDS = 21600  # 6 saat
POSITION_CHECK_SECONDS = 30
FULL_SCAN_SECONDS = 300  # 5 dakika
MIN_FINAL_SCORE = 30
MAX_OPEN_POSITIONS = 4
POSITION_USDT_AMOUNT = 20

POSITION_CHECK_SECONDS = 30
FULL_SCAN_SECONDS = 300
PERFORMANCE_REPORT_SECONDS = 21600

STOP_LOSS_PERCENT = 3.0
HARD_STOP_LOSS_PERCENT = 5.0

BREAK_EVEN_PROFIT_PERCENT = 2.0
TRAILING_START_PROFIT_PERCENT = 3.0
TRAILING_ATR_MULTIPLIER = 1.8

WEAK_SCORE_EXIT = 35
DANGER_SCORE_EXIT = 25
PROFIT_PROTECT_SCORE = 40

COOLDOWN_MINUTES = 30